startup = [
	"mkdir ~/.cache/starship",
	"starship init nu | save ~/.cache/starship/init.nu",
	"source ~/.cache/starship/init.nu"
]
prompt = "starship_prompt"

[line_editor]
edit_mode = "vi"
[textview]
true_color = true
